config/routes.rb
Lukasandreas::Application.routes.draw do
  resources :media
  match "media/new/:id" => "media#new";
  match "media/update-ranks" => "media#updateRanks";
  match "projects/admin" => "projects#admin";
  match "projects/update-ranks" => "projects#updateRanks";
  match "projects/admin/destroy:id" => "projects#destroy";
  resources :projects

  root :to => "projects#index"

end

app/models/medium.rb
class Medium < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  require 'net/http'

  def getVimeoCodeForURL( urlString )
    url = URI.parse( urlString)
    req = Net::HTTP::Get.new(url.path)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
  end

  protected
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "lukas" && password == "andreas"
    end
  end

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_filter :authenticate
  #skip_before_filter :authenticate, :only => [:index, :destroy]


  require 'fileutils'

  # GET /media
  # GET /media.xml
  def index
    @media = Medium.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @media }
    end
  end

  def updateRanks
    @project = Project.find(params[:project_id])
    @allMedia = Medium.find_all_by_project_id(@project.id);

    @allMedia.each { |media|
      media.rank = params[ media.id.to_s() ].to_i();
      media.save;
    }

    respond_to do |format|
      format.html  { render :xml => @allMedia, :status => :created}
    end
  end

  # GET /media/1
  # GET /media/1.xml
  def show
    @medium = Medium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @medium }
    end
  end

  # GET /media/new
  # GET /media/new.xml
  def new
    @medium = Medium.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @medium }
    end
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
  end

  # POST /media
  # POST /media.xml
  def create

    # If it's an image place it into the content directory and create a new url
    if( params[:medium][:category] == "image")
      tmp = params[:my_file];
      directory = 'content'
      newFileName = String(Time.now.to_i) + File.extname(tmp.original_filename);
      newFilePath = Rails.root.join('public', directory, newFileName)
      File.open(newFilePath, 'w') { |file|
        file.write(tmp.read)
      }
      # Remove the attribute from params and set the url
      params[:medium].delete('my_file');
      params[:medium][:url] = directory + "/" + newFileName;
    end

    @medium = Medium.new( params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { render :xml => @medium, :status => :created, :location => @medium }
        format.js   { render :xml => @medium, :status => :created, :location => @medium }
        format.xml  { render :xml => @medium, :status => :created, :location => @medium }
      else
        format.html { render :xml => @medium, :status => :created, :location => @medium }
        format.js   { render :xml => @medium, :status => :created, :location => @medium }
        format.xml  { render :xml => @medium, :status => :created, :location => @medium }
      end
    end
  end

  def file_upload

  end

  # PUT /media/1
  # PUT /media/1.xml
  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to(@medium, :notice => 'Medium was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @medium.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.xml
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to(media_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate
  skip_before_filter :authenticate, :only => [:index, :destroy]

  # GET /roots
  # GET /projects.xml
  def index
    @projects = Project.all(:order => :rank)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects
  # GET /projects.xml
  def admin
    @projects = Project.all(:order => :rank)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  def updateRanks
    @allProjects = Project.all;

    @allProjects.each { |project|
      project.rank = params[ project.id.to_s() ].to_i();
      project.save;
    }

    respond_to do |format|
      format.html  { render :xml => @allProjects, :status => :created}
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    Medium.delete_all(:project_id => @project.id);
    @project.destroy

    respond_to do |format|
      format.html { redirect_to :action=>'admin' }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lukasandreas</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/media.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>LukasAndreas.com &middot; Add Media</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blackrock Global Allocation Fund">
    <meta name="author" content="Ogilvy & Mather for Blackrock">

    <!-- Styles -->
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <% csrf_meta_tag %>
    <link href="/stylesheets/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet/less" type="text/css" href="/stylesheets/styles.less" />
    <script src="/javascripts/thirdparty/less-1.3.3.min.js" type="text/javascript"></script>
</head>
<body style="padding-top: 0;">
<div class="container">
    <%= yield %>
</div>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>LukasAndreas.com &middot; Project List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blackrock Global Allocation Fund">
    <meta name="author" content="Ogilvy & Mather for Blackrock">

    <!-- Styles -->
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <% csrf_meta_tag %>
<%= yield %>
    <script src="/javascripts/thirdparty/less-1.3.3.min.js" type="text/javascript"></script>

app/views/media/_form.html.erb
<%= form_for(@medium, :html => {:multipart => true}) do |f| %>
    <% if @medium.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>

            <ul>
                <% @medium.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :type %>
        <br/>
        <%= f.text_field :type %>
    </div>

    <%= f.file_field :my_file %>

    <!--<input id="fileupload" type="file" name="files[]" data-url="fileserver/php/" multiple>-->
    <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>-->
    <!--<script src="../javascripts/upload/jquery.ui.widget.js"></script>-->
    <!--<script src="../javascripts/upload/jquery.iframe-transport.js"></script>-->
    <!--<script src="../javascripts/upload/jquery.fileupload.js"></script>-->
    <script>
//        $(function () {
//            $('#fileupload').fileupload({
//                dataType: 'json',
//                done: function (e, data) {
//                    $.each(data.result.files, function (index, file) {
//                        $('<p/>').text(file.name).appendTo(document.body);
//                    });
//                },
//                progressall: function (e, data) {
//                    var progress = parseInt(data.loaded / data.total * 100, 10);
//                    $('#progress .bar').css(
//                            'width',
//                            progress + '%'
//                    );
//                }
//            });
//        });
    </script>
    <div id="progress">
        <div class="bar" style="width: 0%; height: 18px; background: green;"></div>
    </div>
    <!--<div class="field">-->
    <%#= f.label :url %><br />
    <%#= f.text_field :url %>
    <!--</div>-->
    <div class="field">
        <%= f.label :caption %>
        <br/>
        <%= f.text_field :caption %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing medium</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Url</th>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @media.each do |medium| %>
  <tr>
    <td><%= medium.category %></td>
    <td><%= medium.url %></td>
    <td><%= medium.caption %></td>
    <td><%= link_to 'Show', medium %></td>
    <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
    <td><%= link_to 'Destroy', medium, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medium', new_medium_path %>

app/views/media/new.html.erb
<%= form_for(@medium, :html => {:multipart => true}) do |f| %>
    <% if @medium.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@medium.errors.count, "error") %> prohibited this medium from being saved:</h2>
            <ul>
                <% @medium.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= hidden_field_tag('medium[category]', 'image')%>
    <%= hidden_field_tag('medium[project_id]', params[:project])%>
    <div class="row">
        <div class="span2">
            <h2>Caption</h2>
        </div>
        <div class="span6 titleInputContainer">
            <%= f.text_field :caption, :class => 'titleInput' %>
        </div>
    </div>
<div class="row">
    <div class="span2">
        <h2>Type</h2>
    </div>
    <div class="span4" style="padding-top:15px">
        <div class="btn-group" data-toggle="buttons-radio">
            <button data-type="image" type="button" class="btn btn-primary" data-toggle="button">Image</button>
            <button data-type="video" type="button" class="btn btn-primary" data-toggle="button">Video</button>
        </div>
    </div>
</div>
    <div class="row" id="imageUpload"  style="display:none;">
        <div class="span2">
            <h3>Upload:</h3>
        </div>
        <div class="span5 formImageUpload">
            <input id="fileupload" type="file" name="my_file" data-url="/media" />
            <%#= f.file_field :my_file %>
        </div>
    </div>
    <div class="row" id="videoUpload" style="display:none;">
        <div class="span2">
            <h3>vimeo url:</h3>
        </div>
        <div class="span6 titleInputContainer">
            <input class="titleInput" id="medium_url" name="medium[url]" size="30" type="text">
        </div>
    </div>
    <!--<div class="hero-unit" id="hero-container">-->
        <!--<h1>Preview</h1>-->
    <!--</div>-->

    <div class="row" style="margin-top:20px">
        <div class="span2">
            <%= f.submit "Add Media", :class => "btn btn-primary"%>
        </div>
    </div>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function(){
        var children = $('div.btn-group')[0].children;
        for(var i = 0; i < children.length; i++ ) {
            $(children[i]).click(function(){

                // Update the hidden form field
                $('#medium_category').val( $(this).data('type') );

                // Show/hide the image/video add buttons
                $('#'+ $(this).data('type') + 'Upload').show();
                $('#'+ $(this.other).data('type') + 'Upload').hide();
            });

            children[i].other = (i == 0) ? children[1] : children[0];
        }

        $('#new_medium').submit(function( event ){
            event.preventDefault();
            var serializedArray = $('#new_medium').serializeArray();
            var formData = new FormData();
            for(var i = 0; i < serializedArray.length; i++) {
                formData.append(serializedArray[i].name, serializedArray[i].value);
            }
            formData.append("my_file", document.getElementById('fileupload').files[0]);

            var req = new XMLHttpRequest();
            req.onreadystatechange = function() {
                if (req.readyState === 4){
                    // Refresh if in iframe
                    if( parent != window ) {
                        parent.location.reload();
                    }
                }
            };
            req.open("POST", "/media");
            req.send(formData);
        });
    }, false);
</script>

    <script src="/javascripts/upload/jquery.ui.widget.js"></script>
    <script src="/javascripts/upload/jquery.iframe-transport.js"></script>
    <script src="/javascripts/upload/jquery.fileupload.js"></script>
<% end %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @medium.type %>
</p>

<p>
  <b>Url:</b>
  <%= @medium.url %>
</p>

<p>
  <b>Caption:</b>
  <%= @medium.caption %>
</p>


<%= link_to 'Edit', edit_medium_path(@medium) %> |
<%= link_to 'Back', media_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= hidden_field_tag('project_id', @project.id)%>
    <div class="row">
        <div class="span2">
            <h2><%= f.label :name %></h2>
        </div>
        <div class="span6 titleInputContainer">
            <%= f.text_field :name, :class => 'titleInput' %>
        </div>
    </div>
    <div class="row">
        <div class="span2">
            <h2><%= f.label :footer %></h2>
        </div>
        <div class="span6 titleInputContainer">
            <%= f.text_field :footer, :class => 'titleInput' %>
        </div>
    </div>
    <div id="newMedia" class="row" style="margin-bottom: 10px;">
        <% unless @project.id.nil? %>
            <button id="addMedia" type="button" class="btn btn-primary">Add Media</button>
        <% end %>
        <div id="newMediaHeader" style="display:none;">
            <h3 style="color:#ff0000;">Media Details</h3>
        </div>
    </div>
    <div id="mediaContainer" class="row">
        <% allMedia= Medium.find_all_by_project_id(@project.id, :order => :rank) %>
        <% allMedia.each do |media| %>
            <div class="form_mediaContainer span3" id="<%=media.id%>_container">
                <% if media.category == "image" %>
                    <img src="/<%= media.url %>" width="100px" />
                <% else %>
                    <%
                       urlString = "http://vimeo.com/api/oembed.json?url=" << media.url << "&width=600"
                       url = URI.parse(urlString)
                       req = Net::HTTP::Get.new(urlString)
                       res = Net::HTTP.start(url.host, url.port) {|http|
                         http.request(req)
                       }
                       #puts url.url
                       json = ActiveSupport::JSON.decode(res.body)
                    %>
                    <%= raw(json['html']) %>
                <% end %>
                <a class="btn btn-danger" id="<%=media.id%>_delete" href="#" style="padding:1px 1px; vertical-align: top;"><i class="icon-trash icon-large"></i></a>
                <input id="<%=media.id%>_rank" type="text" placeholder="<%= media.rank %>" style="width:20px; text-align:center; vertical-align: top;"></input>
            </div>
        <% end %>
    </div>
    <div class="row" style="margin-top:20px">
        <div class="span2">
            <button id="updateMedia" type="button" class="btn btn-warning" style="width:150px">Save Media Order</button>
        </div>
        <div class="span1">
        <%= f.submit "Save Info", :id => "save", :class => "btn btn-info"%>
        </div>
    </div>
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function(){
            $($('#addMedia')[0]).click(function() {
                var container = document.getElementById('newMedia');
                var iframe  = document.createElement("IFRAME");
                iframe.src = "/media/new?project=<%= @project.id %>";
                iframe.style.border = "none";
                container.style.width = iframe.style.width = "980px";
                container.style.height = iframe.style.height = "730px";
                container.appendChild(iframe);

                $(this).remove();
                $("#save").remove();
                $("#newMediaHeader").show();
            });
        }, false);

        /*
         var confirm = window.confirm("Will erase previous data\nAre you sure?");
         if (!confirm) {
            return;
         }
         */
        $(".icon-trash").click(function( event ){
            var confirm = window.confirm("About to destroy this media object!\nAre you sure?");
            if (!confirm) {
                return;
            }

            var formData = new FormData();
            formData.append("_method", "delete");
            var req = new XMLHttpRequest();
            req.onreadystatechange = function( e ) {
                if (req.readyState === 4){
                    // Refresh if in iframe
                    parent.location.reload();
                }
            };
            req.open("POST", "/media/" + this.parentNode.id.split("_")[0] + ".xml");
            req.send(formData);
        })
        $('#updateMedia').click(function( event ){
            event.preventDefault();

            var formData = new FormData();
            formData.append("project_id", $("#project_id")[0].value);
            $(".form_mediaContainer").each(function(index, element){
                var nameParts = element.id.split("_container");
                var rankElement = $("#" + nameParts[0] + "_rank");
                formData.append(nameParts[0], rankElement[0].value || rankElement[0].placeholder);
            });
            var req = new XMLHttpRequest();
            req.onreadystatechange = function( e ) {
                if (req.readyState === 4){
                    // Refresh if in iframe
                    parent.location.reload();
                }
            };
            req.open("POST", "/media/update-ranks");
            req.send(formData);
        });
    </script>
<% end %>

app/views/projects/admin.html.erb
<link rel="stylesheet/less" type="text/css" href="/stylesheets/styles.less" />
</head>
<body>
<!-- Part 1: Wrap all page content here -->
<div id="wrap">
    <!-- Begin page content -->
    <div class="container">

        <div class="page-header">
            <h1>Projects</h1>
            <ul class="nav nav-pills">
                <li class="active" id="updateRanks" style="padding-right:10px"><a href="#" style="background-color:rgb(21, 207, 13)">Save Project Order</a></li>
                <li class="active"></li>
                <li class="active"><%= link_to 'New Project', new_project_path %></li>
            </ul>
        </div>
        <form accept-charset="UTF-8" action="/projects/update-ranks" class="" id="update_form" method="post">
            <% @projects.each do |project| %>
                <div id="<%= project.id %>_container" class="row project">
                    <div class="span0" style="padding-top:14px">
                        <input id="<%=project.id%>_rank" type="text" placeholder="<%= project.rank %>" style="width:20px; text-align:center; vertical-align: top;"></input>

                    </div>
                    <div class="span8 titleInputContainer">
                        <h3><%= project.name %></h3>
                    </div>
                    <%#= link_to 'Show', project %>
                    <div class="span0" style="padding-top:14px">
                        <a class="btn btn-primary" id="" href="/projects/<%= project.id %>/edit" style="padding:4px 4px; vertical-align: top;"><i class="icon-edit icon-large"></i></a>
                        <a class="btn btn-danger" id="<%=project.id%>_delete" href="#" style="padding:4px 4px; vertical-align: top;"><i class="icon-trash icon-large"></i></a>
                    </div>
                </div>
            <% end %>
            <br>

            <br />
            <br />
            <br />
            <br />
        </form>
    </div>
</div>
<div id="footer">
    <div class="container">
        <p>&copy; LukasAndreas 2012</p>
    </div>
</div>
</body>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function(){

    $(".icon-trash").click(function( event ){
        var confirm = window.confirm("About to destroy this project!\nAre you sure?");
        if (!confirm) {
            return;
        }
        var formData = new FormData();
        formData.append("_method", "delete");
        var req = new XMLHttpRequest();
        req.onreadystatechange = function( e ) {
            if (req.readyState === 4){
                // Refresh if in iframe
                parent.location.reload();
            }
        };
        req.open("POST", "/projects/" + this.parentNode.id.split("_")[0] + ".xml");
        req.send(formData);
    })
        $('#updateRanks').click(function( event ){
            event.preventDefault();
            var formData = new FormData();
            $('.project').each(function(index, element){
                console.log(element);
                var nameParts = element.id.split("_container");
                var rankElement = $("#" + nameParts[0] + "_rank");
                formData.append(nameParts[0], rankElement[0].value || rankElement[0].placeholder);
            });
            var req = new XMLHttpRequest();
            req.onreadystatechange = function( e ) {
                if (req.readyState === 4){
                    parent.location.reload();
                }
            };
            req.open("POST", "/projects/update-ranks");
            req.send(formData);
        });
    });
</script>

</html>

app/views/projects/edit.html.erb
<link rel="stylesheet/less" type="text/css" href="/stylesheets/styles.less" />
</head>
<body>
<!-- Part 1: Wrap all page content here -->
<div id="wrap">
    <!-- Begin page content -->
    <div class="container">
        <div class="page-header">
            <h1>Editing project</h1>
            <%= link_to "Back", :controller => "projects", :action => "admin" %>
        </div>
        <%= render 'form' %>
    </div>
</div>
<div id="footer">
    <div class="container">
        <p>&copy; LukasAndreas 2012</p>
    </div>
</div>
</body>
</html>

app/views/projects/index.html.erb
<% require 'net/http' %>
<link rel="stylesheet/less" type="text/css" href="/stylesheets/main.less" />
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top navHeader">
    <div class="navbar-inner lukasAndreasNav" style="background: white;border: none; box-shadow: none;">
        <div class="container" style="max-width:100%; width:730px">
            <div class="nav-collapse collapse">
                <ul class="nav" style="width: 100%;">
                    <% @projects.each do |project| %>
                        <li><a class="projectNavLink" id="<%= project.name.gsub(/[^0-9a-z]/i, '') %>_link" href=""><%= project.name %></a></li>
                    <% end %>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Part 1: Wrap all page content here -->
<div id="wrap">
    <!-- Begin page content -->
    <div class="container">
        <div class="mediaContainer row" style="padding-bottom:10px">
            <img src="/images/hero.jpg" />
        </div>
        <div class="container">
        <% @projects.each do |project| %>
                <div class="mediaContainer row" id="<%= project.name.gsub(/[^0-9a-z]/i, '') %>_content">
                </div>
            <% allMedia= Medium.find_all_by_project_id(project.id) %>
            <% allMedia.each do |media| %>

                    <% if media.category == "image" %>
                  <div class="mediaContainer row">
                        <img src="/<%= media.url %>" />
                    <% else %>
                  <div class="mediaContainer row videoContainer">
                        <%
                           urlString = "http://vimeo.com/api/oembed.json?url=" << media.url << "&width=600"
                           url = URI.parse(urlString)
                           req = Net::HTTP::Get.new(urlString)
                           res = Net::HTTP.start(url.host, url.port) {|http|
                             http.request(req)
                           }
                           #puts url.url
                           json = ActiveSupport::JSON.decode(res.body)
                        %>
                        <%= raw(json['html']) %>
                    <% end %>

                    <% unless media.caption.empty? %>

                    <% end %>
                </div>
            <% end %>
              <div class="projectFooter row">
                  <div class="projectFooterCopy">
                      <%= project.footer.html_safe %>
                  </div>
              </div>
        <% end %>
        </div>
    </div>
    <div id="push"></div>
</div>
<div id="footer">
    <div class="container" style="width:630px;">
        <p class="muted credit">&copy; Lukas Lund & Andreas Hoff <%= Time.now.year %>.</p>
    </div>
</div>
<script type="text/javascript">
    (function() {
        var lastTime = 0;
        var vendors = ['ms', 'moz', 'webkit', 'o'];
        for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
            window.requestAnimationFrame = window[vendors[x]+'RequestAnimationFrame'];
            window.cancelAnimationFrame = window[vendors[x]+'CancelAnimationFrame']
                    || window[vendors[x]+'CancelRequestAnimationFrame'];
        }

        if (!window.requestAnimationFrame)
            window.requestAnimationFrame = function(callback, element) {
                var currTime = new Date().getTime();
                var timeToCall = Math.max(0, 16 - (currTime - lastTime));
                var id = window.setTimeout(function() { callback(currTime + timeToCall); },
                        timeToCall);
                lastTime = currTime + timeToCall;
                return id;
            };

        if (!window.cancelAnimationFrame)
            window.cancelAnimationFrame = function(id) {
                clearTimeout(id);
            };
    }());

    function animate() {
        requestAnimationFrame( animate ); // js/RequestAnimationFrame.js needs to be included too.
        TWEEN.update();
    }
    animate();

    document.addEventListener('DOMContentLoaded', function(){
        console.log( $('.projectNavLink') );
        $('.projectNavLink').click(function(e) {
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();

            var navLink = e.originalEvent.currentTarget;
            var contentId = navLink.id.split("_")[0] + "_content";
            var contentDiv = $('#' + contentId )[0];
            var tween = new TWEEN.Tween( { y: window.scrollY } )
                    .to( { y: contentDiv.offsetTop - 60 }, 1000 )
                    .easing( TWEEN.Easing.Quadratic.InOut )
                    .onUpdate( function () {
                        window.scrollTo( 0, Math.round(this.y) )
                    } )
                    .start();

        });
    }, false);


</script>

app/views/projects/new.html.erb
<link rel="stylesheet/less" type="text/css" href="/stylesheets/styles.less" />
</head>
<body>
<!-- Part 1: Wrap all page content here -->
<div id="wrap">
    <!-- Begin page content -->
    <div class="container">

        <h1>New project</h1>

        <%= render 'form' %>

        <%#= link_to 'Back', projects_path %>
    </div>
</div>
<div id="footer">
    <div class="container">
        <p>&copy; LukasAndreas 2012</p>
    </div>
</div>
</body>
</html>

app/views/projects/show.html.erb
<link rel="stylesheet/less" type="text/css" href="/stylesheets/styles.less" />
</head>
<body>
<!-- Part 1: Wrap all page content here -->
<div id="wrap">
    <!-- Begin page content -->
    <div class="container">
        <p id="notice"><%= notice %></p>

        <p>
            <b>Name:</b>
            <%= @project.name %>
        </p>
        <p>
            <b>Footer:</b>
            <%= @project.footer %>
        </p>
        <%= link_to "Ok great! - Take Me Back", :controller => "projects", :action => "admin" %>

    </div>
</div>
<div id="footer">
</div>
</body>
</html>